# Generated by Django 3.1.3 on 2020-11-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='resposta_aberta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
