# Generated by Django 3.1.3 on 2020-11-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0002_auto_20201106_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'verbose_name': 'Inscrições', 'verbose_name_plural': 'Inscrição'},
        ),
        migrations.RenameField(
            model_name='resposta',
            old_name='incricao',
            new_name='inscricao',
        ),
        migrations.AlterField(
            model_name='resposta',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='inscricoes'),
        ),
    ]
