# Generated by Django 3.1.3 on 2020-11-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0003_auto_20201109_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='has_arquivo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='is_aberta',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
