# Generated by Django 3.1.3 on 2020-11-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0005_edital_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='editais/banner'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='editais/pdf'),
        ),
    ]
