# Generated by Django 3.1.3 on 2020-12-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0006_auto_20201118_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('ap', 'Aprovado'), ('re', 'Reprovado'), ('an', 'Analise'), ('fn', 'Finalizda')], default='an', max_length=2),
        ),
    ]
