# Generated by Django 3.1.3 on 2020-12-03 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0007_auto_20201203_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='alternativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editais.alternativa'),
        ),
    ]
