# Generated by Django 3.1.3 on 2020-12-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0008_auto_20201203_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('ap', 'Aprovado'), ('re', 'Reprovado'), ('an', 'Analise')], default='an', max_length=2),
        ),
    ]
